title: thoughts out loud
description: I have thoughts, sometimes.
show_excerpts: true
url: "https://thoughts.kream.io"
author: Klemen Košir
email: klemen.kosir@kream.io
github_username: KarboniteKream
twitter_username: KarboniteKream
google_analytics: UA-85731271-2

theme: minima

plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/bundle

sass:
  style: compressed
