title: thoughts out loud
description: I have thoughts, sometimes.
url: "https://thoughts.kream.io"
email: klemen.kosir@kream.io
github_username: KarboniteKream
google_analytics: UA-85731271-2

theme: minima

plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  style: compressed
