---
title: thoughts out loud
description: I have thoughts, sometimes.
date_format: "%B %-d, %Y"
url: "https://kream.io"

author: Klemen Košir
email: klemen.kosir@kream.io
github_username: KarboniteKream
bluesky_username: karbonite.kream.io

include:
  - _pages

sass:
  style: compressed
